export const MAIN_TEMPLATE_EMAIL = 'pcdsantos007@gmail.com';

// 2026-03-02 (Seg Carnaval) removido: FIEC teve aula nesse dia
export const FERIADOS_2026 = new Set([
  '2026-01-01','2026-03-03',
  '2026-04-03','2026-04-05',
  '2026-04-20','2026-04-21',
  '2026-05-01','2026-06-11',
  '2026-09-07','2026-10-12',
  '2026-11-02','2026-11-15','2026-12-25'
]);

// Template de aulas da conta owner (pcdsantos007)
export const D = {
  'i1':{m:'Aula 1',t:'Entender o que sabem + Formatação Simples',done:true,
    tp:['Conversa inicial — entender o nível de cada aluno','Negrito, Itálico, Sublinhado','Mudar fonte, tamanho e cor do texto','Alinhamentos: esquerda, centro, direita e justificado'],
    arq:[{n:'Atividade Formatação',u:'atividade_formatacao_simples.pdf'}]},
  'i2':{m:'Aula 2',t:'Cabeçalho, Rodapé e Numeração',done:true,
    tp:['Inserir > Cabeçalho — nome do documento','Inserir > Rodapé — endereços ou referências','Inserir > Número de Página'],
    arq:[{n:'Atividade',u:'atividade_cabecalho_rodape_numeracao.pdf'}]},
  'i3':{m:'Aula 3',t:'Sumário e Índices Automáticos',done:true,
    tp:['Aplicar estilos Título 1 e Título 2','Referências > Sumário > Sumário Automático 1','Atualizar sumário após edições'],
    arq:[{n:'Atividade',u:'Atividade_sumario_indices.pdf'}]},
  'i4':{m:'Aula 4',t:'Atividade Geral',done:true,
    tp:['Prática integrando formatação, cabeçalho, rodapé e sumário','Documento completo sobre tema livre'],
    arq:[{n:'Atividade',u:'atividade_geral.pdf'}]},
  'i5':{m:'Aula 5',t:'Aula Final de Word',done:true,
    tp:['Baixar textosemformato.docx e formatar','Exportar em PDF e entregar'],
    arq:[{n:'Instrução',u:'Aula_final_Word.pdf'},{n:'Passo a Passo',u:'Passo_a_passo.pdf'},{n:'Exemplo Final',u:'Exemplo-resultadoFinal.pdf'}]},
  'i6':{m:'Aula 6',t:'Google Docs',done:true,
    tp:['Criar documento em docs.google.com','Compartilhamento: Editor, Comentarista, Leitor','Modo Sugestão e Histórico de versões'],
    arq:[{n:'Atividade',u:'atividade_google_docs.pdf'}]},
  'i7':{m:'Aula 7',t:'Introdução ao PowerPoint',done:true,
    tp:['Criar apresentação em branco ou com template','Layouts, inserir texto, imagens e formas','Ctrl+M para novo slide'],
    arq:[{n:'Atividade',u:'atividade_comeco_powerpoint.pdf'}]},
  'i8':{m:'Aula 8',t:'PowerPoint — Animações e Recursos Visuais',done:true,
    tp:['Transições: Aplicar a Todos','Animações de Entrada, Ênfase e Saída','Painel de Animação para definir a ordem'],
    arq:[{n:'Atividade',u:'atividade_powerpoint_animacoes.pdf'}]},
  'i9':{m:'Aula 9',t:'PowerPoint — Recursos Adicionais',done:true,
    tp:['SmartArt: Inserir > SmartArt','Gráficos: Inserir > Gráfico','Inserir áudio e vídeo','Designer Inteligente'],
    arq:[{n:'Atividade',u:'atividade_adicionais_powerpoint.pdf'}]},
  'i10':{m:'Aula 10',t:'PowerPoint — Aula Final',
    tp:['Atividade Pizzaria: 3 slides','Slide 1: capa com fundo vermelho','Slide 2: cardápio com círculo branco','Slide 3: menu de sabores'],
    arq:[{n:'Como Fazer',u:'Como_Fazer_Pizzaria.docx'},{n:'Exemplo',u:'Pizzaria.pptx'}]},
  'i11':{m:'Aula 11',t:'Google Slides',
    tp:['Acessar slides.google.com','Colaboração em tempo real','Q&A com público'],
    arq:[{n:'Atividade',u:'INT_Aula15_GoogleSlides_Atividades.html'}]},
  'i12':{m:'Aula 12',t:'Google Meet + Agenda',
    tp:['Meet: nova reunião, compartilhar tela','Agenda: criar evento com link automático'],
    arq:[{n:'Atividade',u:'INT_Aula16_MeetAgenda_Atividades.html'}]},
  'i13':{m:'Aula 13',t:'Canva — Introdução',
    tp:['Criar conta com Google em canva.com','Personalizar template e baixar como PNG'],
    arq:[{n:'Atividade',u:'INT_Aula17_CanvaIntro_Atividades.html'}]},
  'i14':{m:'Aula 14',t:'Canva — Intermediário',
    tp:['Frames, ícones, Regra das 3 Cores','Animações e exportação PNG/PDF/MP4'],
    arq:[{n:'Atividade',u:'INT_Aula18_CanvaInter_Atividades.html'}]},
  'i15':{m:'Aula 15',t:'Google Forms',
    tp:['Tipos de pergunta: múltipla escolha, escala, caixas','Lógica condicional entre seções'],
    arq:[{n:'Atividade',u:'INT_Aula19_GoogleForms_Atividades.html'}]},
  'i16':{m:'Aula 16',t:'Introdução à IA — ChatGPT',
    tp:['Acessar chat.openai.com ou Copilot no Edge','Como fazer boas perguntas'],
    arq:[{n:'Atividade',u:'INT_Aula20_IA_Atividades.html'}]},
  'i17':{m:'Aula 17',t:'Google Keep + Agenda',
    tp:['Keep: nota, lista de tarefas, lembrete','Agenda: eventos, visualização semanal'],
    arq:[{n:'Atividade',u:'INT_Aula22_KeepAgenda_Atividades.html'}]},
  'i18':{m:'Aula 18',t:'Revisão Prática',
    tp:['Word: documento com capa e sumário','PowerPoint: apresentação com animações','Canva: post com frame e paleta'],
    arq:[{n:'Atividade',u:'INT_Aula23_RevisaoPratica_Atividades.html'}]},
  'i19':{m:'Aula 19',t:'Currículo no Canva',
    tp:['Pesquisar "Currículo" e escolher template','Personalizar: nome, foto, contato','Baixar em PDF para Impressão'],
    arq:[{n:'Atividade',u:'INT_Aula24_Curriculo_Atividades.html'}]},
  'a1':{m:'Aula 1',t:'Introdução ao Excel',done:true,
    tp:['Diagnóstico do nível da turma','Interface: células, linhas, colunas'],
    arq:[{n:'Atividades Avançado (Drive)',u:'https://drive.google.com/drive/folders/1vf9iNttdxdevpELlrWU1k1jrULeN8Rcz?usp=sharing',ext:true}]},
  'a2':{m:'Aula 2',t:'Fórmulas Simples',done:true,
    tp:['Soma, subtração, multiplicação e divisão','Preenchimento automático de fórmulas'],
    arq:[{n:'Atividade 1',u:'atvds_aula3.pdf'},{n:'Atividade 2',u:'atvds2_aula3.pdf'}]},
  'a3':{m:'Aula 3',t:'Funções Simples',done:true,
    tp:['SOMA, MÉDIA, MÍNIMO, MÁXIMO','MULT para multiplicação de intervalo'],
    arq:[{n:'Atividade',u:'atividades_excel_aula1.pdf'}]},
  'a4':{m:'Aula 4',t:'Funções Lógicas',done:true,
    tp:['SE: sintaxe e uso básico','E: todas as condições verdadeiras','OU: basta uma condição'],
    arq:[{n:'Atividade',u:'atividades_funcoes_logicas_excel.pdf'}]},
  'a5':{m:'Aula 5',t:'Lógica Avançada',done:true,
    tp:['SE aninhado: SE dentro de SE','Combinações de SE+E e SE+OU'],
    arq:[{n:'Atividade 1',u:'atvds_aula4.pdf'},{n:'Atividade 2',u:'atvds_2_aula4.pdf'}]},
  'a6':{m:'Aula 6',t:'Referências',done:true,
    tp:['Referência relativa: se move ao copiar','Referência absoluta $A$1: travada com F4'],
    arq:[{n:'Atividade',u:'atvds_fx_ref.txt'}]},
  'a7':{m:'Aula 7',t:'Tabela Dinâmica',done:true,
    tp:['Criar a partir de dados brutos','Áreas: Linhas, Colunas, Valores, Filtros'],
    arq:[{n:'Planilha de Dados',u:'ex-atvd_tab_din.xlsx'},{n:'Enunciado',u:'enunc_atvd_tab_din.txt'}]},
  'a8':{m:'Aula 8',t:'Macros',done:true,
    tp:['Gravar macro: Exibição > Macros > Gravar','Editar no VBA: Alt+F11'],
    arq:[]},
  'a9':{m:'Aula 9',t:'PROCV',done:true,
    tp:['Sintaxe: PROCV(valor, tabela, coluna, 0)','Analogia da lista telefônica'],arq:[]},
  'a10':{m:'Aula 10',t:'Complementar + Revisão para Prova',done:true,
    tp:['Exercícios complementares finais','SE aninhado: revisitar com exemplos','Tabela Dinâmica: montar do zero','Simulado: 2-3 questões estilo prova'],arq:[]},
  'a11':{m:'Aula 11',t:'Prova — Excel',
    tp:['Distribuir arquivo de prova','Duração: 60 a 80 minutos','Conteúdo: SE aninhado, Tabela Dinâmica, Macros'],arq:[]},
  'a12':{m:'Aula 12',t:'Excel — PROCV',
    tp:['Analogia da lista telefônica','4 argumentos: valor, tabela (F4!), coluna, 0','Erros comuns antes dos exercícios'],arq:[]},
  'a13':{m:'Aula 13',t:'Excel — ÍNDICE + CORRESP',
    tp:['Limitação do PROCV: só busca à direita','CORRESP: encontra a posição','ÍNDICE: busca o valor na posição'],arq:[]},
  'a14':{m:'Aula 14',t:'Google Planilhas',
    tp:['Salvamento automático','Cores alternadas: Formatar > Cores alternadas','GOOGLEFINANCE para cotação ao vivo'],arq:[]},
  'a15':{m:'Aula 15',t:'Google Sites + Forms',
    tp:['Sites: criar site arrastando elementos','Embutir gráfico do Sheets no site','Forms conectado ao Sheets'],arq:[]},
  'a16':{m:'Aula 16',t:'IA Dia 1 — Criar',
    tp:['ChatGPT: pedir fórmula de Excel','Gamma App: gerar apresentação inteira','SunoAI: gerar música com letra'],arq:[]},
  'a17':{m:'Aula 17',t:'IA Dia 2 — Pesquisar',
    tp:['NotebookLM: carregar apostila e fazer perguntas','Perplexity: pesquisa com fontes citadas','Napkin.ai: texto vira infográfico'],arq:[]},
  'a18':{m:'Aula 18',t:'Excel no Dia a Dia',
    tp:['Planilha de gastos pessoais do zero','SOMA entradas, saídas, SALDO','Gráfico de pizza por categoria'],arq:[]},
  'a19':{m:'Aula 19',t:'Revisão Excel',
    tp:['Dúvidas de PROCV, ÍNDICE+CORRESP, SE e Tabela Dinâmica','Resolver dúvidas individualmente'],arq:[]},
  'enc':{m:'Aula 20',t:'Encerramento',enc:true,
    tp:['Sem matéria hoje! Dia de comemorar o fim do módulo','Aproveitem 🎉'],arq:[]}
};
